artist:
  name: El Perfil
  tagline: Tradiciones Milenarias
  # seo_title:
  # seo_description:
  # contact_twitter_username:
  # contact_phone: 
  # contact_email: 

social:
  - name: Facebook
    url: https://www.facebook.com/ElPerfilSGO/?ref=bookmarks
  - name: Instagram
    url: https://www.instagram.com/elperfiloficial/
  - name: Youtube
    url: https://www.youtube.com/channel/UCG5RJmWFsUbjsNEG_8p1f5Q
  - name: Spotify
    url: https://open.spotify.com/artist/06aNyu6LRacEalrWpQ4Iuw?si=HQDtaayfQCOR6CEpihuxIw

site_language: es
